"""Add constraints to base model

Revision ID: d2b5d4fbcffd
Revises: f0e8589dab88
Create Date: 2025-11-18 20:33:14.650671

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'd2b5d4fbcffd'
down_revision = 'f0e8589dab88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
