"""Change models

Revision ID: f0e8589dab88
Revises: aeb720972009
Create Date: 2025-11-17 00:08:18.355666

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'f0e8589dab88'
down_revision = 'aeb720972009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
