"""add_donation_and_related_models

Revision ID: aeb720972009
Revises: 63dd57e1f00c
Create Date: 2025-11-16 13:03:07.112321

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'aeb720972009'
down_revision = '63dd57e1f00c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
